package:
  name: scarmapper
  version: "3.0.0"

source:
  path: ..

build:
  noarch: python
  script: pip install . --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=68.0
    - cython >=3.0
  run:
    - python >=3.8
    - pear >=0.9.6
    - scipy >=1.7.0
    - natsort >=8.0.0
    - python-magic >=0.4.24
    - pysam >=0.18.0
    - pathos >=0.2.8
    - numpy >=1.20.0
    - pandas >=1.3.0
    - matplotlib >=3.4.0
    - pyfaidx >=0.7.0
    - python-levenshtein >=0.12.2

about:
  home: https://github.com/Gaorav-Gupta-Lab/ScarMapper
  license: MIT
  summary: Classify double-strand DNA break repair products
